# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'DemoLocation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
   pod 'RxSwift', '6.2.0'
   pod 'RxCocoa', '6.2.0'
   pod 'NSObject+Rx'
   pod 'SwiftMessages'
   pod 'GoogleMaps'
   pod 'GooglePlaces'
   pod 'GeoFire'#, :git => 'https://github.com/firebase/geofire-objc.git'
   pod 'SideMenu'
end

post_install do |installer|
      installer.pods_project.targets.each do |target|
           target.build_configurations.each do |config|
                config.build_settings['CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF'] = 'NO'
                config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
                config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
           end
      end
 end
